# URLs JW.org - Bible complète Mooré & Français (66 livres)
# Seuls les 8 livres manquants sont à scraper (les 58 autres sont déjà en cache)

BASE_MOORE = "https://www.jw.org/mos/d-s%E1%BA%BDn-yiisi/biible/nwt/books/"
BASE_FRENCH = "https://www.jw.org/fr/biblioth%C3%A8que/bible/bible-d-etude/livres/"
BASE_ENGLISH = "https://www.jw.org/en/library/bible/study-bible/books/"

# ============================================================
# 8 LIVRES MANQUANTS — À scraper
# ============================================================
URLS_MOORE_MISSING = {
    "zak":        BASE_MOORE + "zak/1/",
    "1-piyeer":   BASE_MOORE + "1-P%C9%A9y%C9%9B%C9%9Br/1/",
    "2-piyeer":   BASE_MOORE + "2-P%C9%A9y%C9%9B%C9%9Br/1/",
    "1-za":       BASE_MOORE + "1-Z%C3%A3/1/",
    "2-za":       BASE_MOORE + "2-Z%C3%A3/1/",
    "3-za":       BASE_MOORE + "3-Z%C3%A3/1/",
    "ziid":       BASE_MOORE + "ziid/1/",
    "venegre":    BASE_MOORE + "V%E1%BA%BDnegre/1/",
}

URLS_FRENCH_MISSING = {
    "jacques":    BASE_FRENCH + "Jacques/1/",
    "1-pierre":   BASE_FRENCH + "1-Pierre/1/",
    "2-pierre":   BASE_FRENCH + "2-Pierre/1/",
    "1-jean":     BASE_FRENCH + "1-Jean/1/",
    "2-jean":     BASE_FRENCH + "2-Jean/1/",
    "3-jean":     BASE_FRENCH + "3-Jean/1/",
    "jude":       BASE_FRENCH + "Jude/1/",
    "apocalypse": BASE_FRENCH + "Apocalypse/1/",
}

# ============================================================
# BIBLE COMPLÈTE — Référence (58 déjà scrapés + 8 manquants)
# ============================================================
URLS_MOORE = {
    # Ancien Testament
    "genese":       BASE_MOORE + "S%C9%A9ngre/1/",
    "exode":        BASE_MOORE + "yikri/1/",
    "levitique":    BASE_MOORE + "Maan-k%CA%8B%CA%8Bre/1/",
    "nombres":      BASE_MOORE + "S%C3%B5dbo/1/",
    "deuteronome":  BASE_MOORE + "T%C3%B5odo/1/",
    "josue":        BASE_MOORE + "zozuwe/1/",
    "juges":        BASE_MOORE + "B%CA%8B-kaoodb%C3%A3/1/",
    "rut":          BASE_MOORE + "rut/1/",
    "1-samuel":     BASE_MOORE + "1-S%C3%A3mw%C9%9Bll/1/",
    "2-samuel":     BASE_MOORE + "2-S%C3%A3mw%C9%9Bll/1/",
    "1-rois":       BASE_MOORE + "1-R%C4%A9m-d%C3%A3mb%C3%A3/1/",
    "2-rois":       BASE_MOORE + "2-R%C4%A9m-d%C3%A3mb%C3%A3/1/",
    "1-chroniques": BASE_MOORE + "1-Kibay%C3%A3/1/",
    "2-chroniques": BASE_MOORE + "2-Kibay%C3%A3/1/",
    "esdras":       BASE_MOORE + "%C6%90sdras/1/",
    "nehemie":      BASE_MOORE + "neemi/1/",
    "esther":       BASE_MOORE + "%C6%90st%C9%9B%C9%9Br/1/",
    "job":          BASE_MOORE + "zoob/1/",
    "psaumes":      BASE_MOORE + "Y%C9%A9%C9%A9n-s%C3%B5amy%C3%A3/1/",
    "proverbes":    BASE_MOORE + "Yel-b%C5%A9n%C3%A3/1/",
    "ecclesiaste":  BASE_MOORE + "Ko%C9%9B%C9%9Bg-soaba/1/",
    "cantique":     BASE_MOORE + "Salomo-y%C9%A9%C9%A9ll%C3%A3/1/",
    "isaie":        BASE_MOORE + "ezayi/1/",
    "jeremie":      BASE_MOORE + "zeremi/1/",
    "lamentations": BASE_MOORE + "wiisgu/1/",
    "ezechiel":     BASE_MOORE + "Ezek%C9%A9y%C9%9Bll/1/",
    "daniel":       BASE_MOORE + "D%C3%A3niy%C9%9Bll/1/",
    "osee":         BASE_MOORE + "ooze/1/",
    "joel":         BASE_MOORE + "Zow%C9%9Bll/1/",
    "amos":         BASE_MOORE + "amos/1/",
    "abdias":       BASE_MOORE + "abdiyaas/1/",
    "jonas":        BASE_MOORE + "zonas/1/",
    "michee":       BASE_MOORE + "mise/1/",
    "nahum":        BASE_MOORE + "nahum/1/",
    "habacuc":      BASE_MOORE + "habakuk/1/",
    "sophonie":     BASE_MOORE + "sofoni/1/",
    "aggee":        BASE_MOORE + "aaze/1/",
    "zacharie":     BASE_MOORE + "zakari/1/",
    "malachie":     BASE_MOORE + "malaki/1/",
    # Nouveau Testament
    "matthieu":         BASE_MOORE + "matiye/1/",
    "marc":             BASE_MOORE + "mark/1/",
    "luc":              BASE_MOORE + "luk/1/",
    "jean":             BASE_MOORE + "Z%C3%A3/1/",
    "actes":            BASE_MOORE + "T%CA%8B%CA%8Bma/1/",
    "romains":          BASE_MOORE + "Rom-d%C3%A3mb%C3%A3/1/",
    "1-corinthiens":    BASE_MOORE + "1-Kor%E1%BA%BDnt-r%C3%A3mb%C3%A3/1/",
    "2-corinthiens":    BASE_MOORE + "2-Kor%E1%BA%BDnt-r%C3%A3mb%C3%A3/1/",
    "galates":          BASE_MOORE + "Galat-r%C3%A3mb%C3%A3/1/",
    "ephesiens":        BASE_MOORE + "Ef%C9%9B%C9%9Bz-r%C3%A3mb%C3%A3/1/",
    "philippiens":      BASE_MOORE + "Filip-r%C3%A3mb%C3%A3/1/",
    "colossiens":       BASE_MOORE + "Kolos-r%C3%A3mb%C3%A3/1/",
    "1-thessaloniciens":BASE_MOORE + "1-Tesalonik-r%C3%A3mb%C3%A3/1/",
    "2-thessaloniciens":BASE_MOORE + "2-Tesalonik-r%C3%A3mb%C3%A3/1/",
    "1-timothee":       BASE_MOORE + "1-T%C9%A9mote/1/",
    "2-timothee":       BASE_MOORE + "2-T%C9%A9mote/1/",
    "tite":             BASE_MOORE + "T%C9%A9te/1/",
    "philemon":         BASE_MOORE + "filemo/1/",
    "hebreux":          BASE_MOORE + "Ebre-r%C3%A3mb%C3%A3/1/",
    # 8 manquants
    "jacques":          BASE_MOORE + "zak/1/",
    "1-pierre":         BASE_MOORE + "1-P%C9%A9y%C9%9B%C9%9Br/1/",
    "2-pierre":         BASE_MOORE + "2-P%C9%A9y%C9%9B%C9%9Br/1/",
    "1-jean":           BASE_MOORE + "1-Z%C3%A3/1/",
    "2-jean":           BASE_MOORE + "2-Z%C3%A3/1/",
    "3-jean":           BASE_MOORE + "3-Z%C3%A3/1/",
    "jude":             BASE_MOORE + "ziid/1/",
    "apocalypse":       BASE_MOORE + "V%E1%BA%BDnegre/1/",
}

URLS_FRENCH = {
    # Ancien Testament
    "genese":       BASE_FRENCH + "Gen%C3%A8se/1/",
    "exode":        BASE_FRENCH + "Exode/1/",
    "levitique":    BASE_FRENCH + "L%C3%A9vitique/1/",
    "nombres":      BASE_FRENCH + "Nombres/1/",
    "deuteronome":  BASE_FRENCH + "Deut%C3%A9ronome/1/",
    "josue":        BASE_FRENCH + "Josu%C3%A9/1/",
    "juges":        BASE_FRENCH + "Juges/1/",
    "rut":          BASE_FRENCH + "Ruth/1/",
    "1-samuel":     BASE_FRENCH + "1-Samuel/1/",
    "2-samuel":     BASE_FRENCH + "2-Samuel/1/",
    "1-rois":       BASE_FRENCH + "1-Rois/1/",
    "2-rois":       BASE_FRENCH + "2-Rois/1/",
    "1-chroniques": BASE_FRENCH + "1-Chroniques/1/",
    "2-chroniques": BASE_FRENCH + "2-Chroniques/1/",
    "esdras":       BASE_FRENCH + "Esdras/1/",
    "nehemie":      BASE_FRENCH + "N%C3%A9h%C3%A9mie/1/",
    "esther":       BASE_FRENCH + "Esther/1/",
    "job":          BASE_FRENCH + "Job/1/",
    "psaumes":      BASE_FRENCH + "Psaumes/1/",
    "proverbes":    BASE_FRENCH + "Proverbes/1/",
    "ecclesiaste":  BASE_FRENCH + "Eccl%C3%A9siaste/1/",
    "cantique":     BASE_FRENCH + "Chant-de-Salomon/1/",
    "isaie":        BASE_FRENCH + "Isa%C3%AFe/1/",
    "jeremie":      BASE_FRENCH + "J%C3%A9r%C3%A9mie/1/",
    "lamentations": BASE_FRENCH + "Lamentations/1/",
    "ezechiel":     BASE_FRENCH + "%C3%89z%C3%A9chiel/1/",
    "daniel":       BASE_FRENCH + "Daniel/1/",
    "osee":         BASE_FRENCH + "Os%C3%A9e/1/",
    "joel":         BASE_FRENCH + "Jo%C3%ABl/1/",
    "amos":         BASE_FRENCH + "Amos/1/",
    "abdias":       BASE_FRENCH + "Abdias/1/",
    "jonas":        BASE_FRENCH + "Jonas/1/",
    "michee":       BASE_FRENCH + "Mich%C3%A9e/1/",
    "nahum":        BASE_FRENCH + "Nahum/1/",
    "habacuc":      BASE_FRENCH + "Habacuc/1/",
    "sophonie":     BASE_FRENCH + "Sophonie/1/",
    "aggee":        BASE_FRENCH + "Agg%C3%A9e/1/",
    "zacharie":     BASE_FRENCH + "Zacharie/1/",
    "malachie":     BASE_FRENCH + "Malachie/1/",
    # Nouveau Testament
    "matthieu":         BASE_FRENCH + "Matthieu/1/",
    "marc":             BASE_FRENCH + "Marc/1/",
    "luc":              BASE_FRENCH + "Luc/1/",
    "jean":             BASE_FRENCH + "Jean/1/",
    "actes":            BASE_FRENCH + "Actes/1/",
    "romains":          BASE_FRENCH + "Romains/1/",
    "1-corinthiens":    BASE_FRENCH + "1-Corinthiens/1/",
    "2-corinthiens":    BASE_FRENCH + "2-Corinthiens/1/",
    "galates":          BASE_FRENCH + "Galates/1/",
    "ephesiens":        BASE_FRENCH + "%C3%89ph%C3%A9siens/1/",
    "philippiens":      BASE_FRENCH + "Philippiens/1/",
    "colossiens":       BASE_FRENCH + "Colossiens/1/",
    "1-thessaloniciens":BASE_FRENCH + "1-Thessaloniciens/1/",
    "2-thessaloniciens":BASE_FRENCH + "2-Thessaloniciens/1/",
    "1-timothee":       BASE_FRENCH + "1-Timoth%C3%A9e/1/",
    "2-timothee":       BASE_FRENCH + "2-Timoth%C3%A9e/1/",
    "tite":             BASE_FRENCH + "Tite/1/",
    "philemon":         BASE_FRENCH + "Phil%C3%A9mon/1/",
    "hebreux":          BASE_FRENCH + "H%C3%A9breux/1/",
    # 8 manquants
    "jacques":          BASE_FRENCH + "Jacques/1/",
    "1-pierre":         BASE_FRENCH + "1-Pierre/1/",
    "2-pierre":         BASE_FRENCH + "2-Pierre/1/",
    "1-jean":           BASE_FRENCH + "1-Jean/1/",
    "2-jean":           BASE_FRENCH + "2-Jean/1/",
    "3-jean":           BASE_FRENCH + "3-Jean/1/",
    "jude":             BASE_FRENCH + "Jude/1/",
    "apocalypse":       BASE_FRENCH + "Apocalypse/1/",
}

URLS_ENGLISH = {
    # Old Testament
    "genese":       BASE_ENGLISH + "Genesis/1/",
    "exode":        BASE_ENGLISH + "Exodus/1/",
    "levitique":    BASE_ENGLISH + "Leviticus/1/",
    "nombres":      BASE_ENGLISH + "Numbers/1/",
    "deuteronome":  BASE_ENGLISH + "Deuteronomy/1/",
    "josue":        BASE_ENGLISH + "Joshua/1/",
    "juges":        BASE_ENGLISH + "Judges/1/",
    "rut":          BASE_ENGLISH + "Ruth/1/",
    "1-samuel":     BASE_ENGLISH + "1-Samuel/1/",
    "2-samuel":     BASE_ENGLISH + "2-Samuel/1/",
    "1-rois":       BASE_ENGLISH + "1-Rois/1/",
    "2-rois":       BASE_ENGLISH + "2-Rois/1/",
    "1-chroniques": BASE_ENGLISH + "1-Chroniques/1/",
    "2-chroniques": BASE_ENGLISH + "2-Chroniques/1/",
    "esdras":       BASE_ENGLISH + "Ezra/1/",
    "nehemie":      BASE_ENGLISH + "Nehemiah/1/",
    "esther":       BASE_ENGLISH + "Esther/1/",
    "job":          BASE_ENGLISH + "Job/1/",
    "psaumes":      BASE_ENGLISH + "Psalms/1/",
    "proverbes":    BASE_ENGLISH + "Proverbs/1/",
    "ecclesiaste":  BASE_ENGLISH + "Ecclesiastes/1/",
    "cantique":     BASE_ENGLISH + "Song-of-Solomon/1/",
    "isaie":        BASE_ENGLISH + "Isaiah/1/",
    "jeremie":      BASE_ENGLISH + "Jeremiah/1/",
    "lamentations": BASE_ENGLISH + "Lamentations/1/",
    "ezechiel":     BASE_ENGLISH + "Ezekiel/1/",
    "daniel":       BASE_ENGLISH + "Daniel/1/",
    "osee":         BASE_ENGLISH + "Hosea/1/",
    "joel":         BASE_ENGLISH + "Joel/1/",
    "amos":         BASE_ENGLISH + "Amos/1/",
    "abdias":       BASE_ENGLISH + "Obadiah/1/",
    "jonas":        BASE_ENGLISH + "Jonah/1/",
    "michee":       BASE_ENGLISH + "Micah/1/",
    "nahum":        BASE_ENGLISH + "Nahum/1/",
    "habacuc":      BASE_ENGLISH + "Habakkuk/1/",
    "sophonie":     BASE_ENGLISH + "Zephaniah/1/",
    "aggee":        BASE_ENGLISH + "Haggai/1/",
    "zacharie":     BASE_ENGLISH + "Zechariah/1/",
    "malachie":     BASE_ENGLISH + "Malachi/1/",
    # New Testament
    "matthieu":         BASE_ENGLISH + "Matthew/1/",
    "marc":             BASE_ENGLISH + "Mark/1/",
    "luc":              BASE_ENGLISH + "Luke/1/",
    "jean":             BASE_ENGLISH + "John/1/",
    "actes":            BASE_ENGLISH + "Acts/1/",
    "romains":          BASE_ENGLISH + "Romans/1/",
    "1-corinthiens":    BASE_ENGLISH + "1-Corinthians/1/",
    "2-corinthiens":    BASE_ENGLISH + "2-Corinthians/1/",
    "galates":          BASE_ENGLISH + "Galatians/1/",
    "ephesiens":        BASE_ENGLISH + "Ephesians/1/",
    "philippiens":      BASE_ENGLISH + "Philippians/1/",
    "colossiens":       BASE_ENGLISH + "Colossians/1/",
    "1-thessaloniciens":BASE_ENGLISH + "1-Thessalonians/1/",
    "2-thessaloniciens":BASE_ENGLISH + "2-Thessalonians/1/",
    "1-timothee":       BASE_ENGLISH + "1-Timothée/1/",
    "2-timothee":       BASE_ENGLISH + "2-Timothée/1/",
    "tite":             BASE_ENGLISH + "Titus/1/",
    "philemon":         BASE_ENGLISH + "Philemon/1/",
    "hebreux":          BASE_ENGLISH + "Hebrews/1/",
    "jacques":          BASE_ENGLISH + "James/1/",
    "1-pierre":         BASE_ENGLISH + "1-Peter/1/",
    "2-pierre":         BASE_ENGLISH + "2-Peter/1/",
    "1-jean":           BASE_ENGLISH + "1-Jean/1/",
    "2-jean":           BASE_ENGLISH + "2-Jean/1/",
    "3-jean":           BASE_ENGLISH + "3-Jean/1/",
    "jude":             BASE_ENGLISH + "Jude/1/",
    "apocalypse":       BASE_ENGLISH + "Revelation/1/",
}
